# Generated by Django 4.1.1 on 2025-01-10 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='f_fabricacion',
            field=models.IntegerField(),
        ),
    ]
