# Generated by Django 4.1.1 on 2025-01-13 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0007_alter_directorgeneral_table_alter_laboratorio_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='directorgeneral',
            table=None,
        ),
        migrations.AlterModelTable(
            name='laboratorio',
            table=None,
        ),
        migrations.AlterModelTable(
            name='producto',
            table=None,
        ),
    ]
