# Generated by Django 4.1.1 on 2025-01-13 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0008_alter_directorgeneral_table_alter_laboratorio_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='directorgeneral',
            table='director_tabla',
        ),
        migrations.AlterModelTable(
            name='laboratorio',
            table='laboratorio_tabla',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='producto_tabla',
        ),
    ]
